### ISSUE TITLE
The new version of irc-message makes the client crash from time to time.

### ISSUE THREAD

**Issue by Schmoopiie** [Schmoopiie/twitch-irc#44]
Not sure why as I didn't have time to look at their update, but sometimes it doesn't send the prefix and makes the client crash with a TypeError.

```
[19:26:46] error - typeerror: cannot call method 'indexof' of null
    at client._handlemessage (c:\users\Schmoopiie\desktop\development\twitch-irc\library\client.js:153:24)
    at stream.emit (events.js:95:17)
    at drain (c:\users\Schmoopiie\desktop\development\twitch-irc\node_modules\through\index.js:36:16)
    at stream.stream.queue.stream.push (c:\users\Schmoopiie\desktop\development\twitch-irc\node_modules\through\index.js:4
5:5)
    at linestream.<anonymous> (c:\users\Schmoopiie\desktop\development\twitch-irc\library\modules\messages.js:42:16)
    at linestream.emit (events.js:95:17)
    at linestream.<anonymous> (_stream_readable.js:764:14)
    at linestream.emit (events.js:92:17)
    at emitreadable_ (_stream_readable.js:426:10)
    at emitreadable (_stream_readable.js:422:5)
```

**Comment by enilsen16** [comment]
:+1: I ran into this issue as well.

**Comment by Schmoopiie** [comment]
Updated in [92b03b3](https://github.com/Schmoopiie/twitch-irc/commit/92b03b3ed0c0a990e8acfeb6132c6bdf0a828819).. I still need to test everything, then I will push the update and also release the new documentation. Hopefully will release a stable version this week.
