### ISSUE TITLE
Hash not stripped in this.moderators object

### ISSUE THREAD

**Issue by designgears** [Schmoopiie/twitch-irc#50]
Error
```
[19:24:15] error - typeerror: cannot read property 'indexof' of undefined at client.ismod (c:\bot\node_modules\twitch-irc\libraries\client.js:631:48)
    at client.<anonymous> (c:\bot\bot.js:29:14)
    at client.emit (events.js:118:17)
    at c:\bot\node_modules\twitch-irc\libraries\client.js:484:30
    at object.createchanneluserdata (c:\bot\node_modules\twitch-irc\libraries\data.js:48:2)
    at client._handlemessage (c:\bot\node_modules\twitch-irc\libraries\client.js:472:22)
    at stream.emit (events.js:107:17)
    at drain (c:\bot\node_modules\twitch-irc\node_modules\through\index.js:36:16)
    at stream.stream.queue.stream.push (c:\bot\node_modules\twitch-irc\node_modules\through\index.js:45:5)
    at linestream.<anonymous> (c:\bot\node_modules\twitch-irc\libraries\modules\messages.js:42:16)
```
```
/* Check if username is moderator on channel */
client.prototype.isMod = function isMod(channel, username) {
    if (this.moderators[utils.remHash(channel)].indexOf(username.toLowerCase()) >= 0) {
        return true;
    }
    return false;
};
```

Console log:
```
{ '#designgears': [] }
```

**Comment by enilsen16** [comment]
It looks like both client.moderators and ModsList are empty... 
```
  moderators: { '#eyeswl': [] },
  myself: 'eyeswl',
  Channels: [ 'eyeswl' ],
  Database: null,
  DBPath: './database',
  Latency: Fri Feb 27 2015 19:56:19 GMT-0800 (PST),
  Tags: false,
  Port: 443,
  CommandError: '',
  ModsList: [],
```

**Comment by enilsen16** [comment]
However as @Schmoopiie says said before I recommend using something like this @designgears -

```javascript
client.addListener('chat', function (channel, user, message) {
    if (user.special.indexOf('mod') >= 0) {
        // User is a mod..
    }
});
```

**Comment by Schmoopiie** [comment]
Updated in [92b03b3](https://github.com/Schmoopiie/twitch-irc/commit/92b03b3ed0c0a990e8acfeb6132c6bdf0a828819).. I still need to test everything, then I will push the update and also release the new documentation. Hopefully will release a stable version this week.
